version: '3.8'

services:
  invite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000" # Mapping host port 3005 to container port 3000
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # - DATABASE_URL=... (for future use)
