name: Mirror to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab Mirror
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          if [ -z "$GITLAB_TOKEN" ]; then
            echo "Ошибка: Секрет GITLAB_TOKEN не задан!"
            exit 1
          fi
          
          # Явно прописываем путь до репозитория в GitLab
          TARGET_URL="https://oauth2:${GITLAB_TOKEN}@gitlab.com/hp-tools/hello-park-invite.git"
          
          git remote add gitlab "$TARGET_URL"
          git push gitlab --all --force
          git push gitlab --tags --force
